var montageSrc = "Example2.jpg";
var xImages = 8;
var yImages = 4;
var xImagePixels = 751;
var yImagePixels = 1334;
var startFrame = 0;
var startZoom = 1;
var startXOffset = 0;
var startYOffset = 0;
//var scale = 1; //uncomment this to disable auto fit
var rotateSensitivity = 0.25;
